#!/bin/env bash
#
# this tool provides port forwarding from the submitted node to the compute node and
# starts the cryosparc-docker-poc container

port=${1:-39000}

echo "Cryosparc will be started on $(hostname) and establish port farwarding from $SLURM_SUBMIT_HOST on port $port"

ssh -N -R ${port}:localhost:${port} $SLURM_SUBMIT_HOST &

apptainer run --bind $HOME/cryosparc-data:/home/$(whoami)/cryosparc \
	--env CRYOSPARC_BASE_PORT=${port} \
	--env CRYOSPARC_LICENSE_ID=${CRYOSPARC_LICENSE_ID} \
	--env LSCRATCH=$TMPDIR \
	--env USERNAME=$(whoami) \
	--env EXTERNAL_UID=$UID \
	--env MAIL=$MAIL \
	--overlay overlay.img --fakeroot cryosparc-docker-poc.sif

