#!/bin/env bash
#
# this tool provides port forwarding from the submitted node to the compute node and
# starts cryosparc-docker-poc container

qos="--qos=job_gpu"

print_help(){
      echo "Usage: $0 port [OPTIONS...] "
      echo " "
      echo "Wrapper to launch the a CryoSPARC server on an UBELIX compute nodes."
      echo "Note: All options are forwarded to SLURM"
      echo "      The port needs to be first argument, then the order is arbitrary"
      echo " "
      echo "options:"
      echo "  -h, --help                       show brief help"
      exit 0
}

### check if called within SLURM allocation
if ! [ -z ${SLURM_JOBID+x} ]; then
  echo "ERROR: it seems that you called $0 from within a SLURM allocation."
  echo "ERROR: $0 needs to be called from the login node and without srun or sbatch. "
  echo " "
  print_help
  exit 0
fi

### get the cryosparc port number, needs to be first argument
port=${1}
[[ $port =~ ^[0-9]+$ ]] || { echo "ERROR: first argument needs to be the selected port number"; print_help; }
if ! (( port >= 2000 && port <= 650000 )); then
   echo "ERROR: the port number needs to be within range [2000,65000]"
   echo " "
   print_help
fi
shift

args=""
### Sort the remaining arguments
###   In general all arguments are consideres as slurm arguments
while test $# -gt 0; do
  case "$1" in
    -h|--help)
      print_help
      ;;
    *)
      args="$args $1"
      shift
      ;;
  esac
done

srun $args cryosparc_remote_port_forward $port
